# Generated by Django 4.0.5 on 2022-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.CharField(default=(5, 9, 2022), max_length=50, verbose_name='Дата публикации'),
        ),
    ]
