# Generated by Django 4.0.5 on 2022-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(default='не задано', max_length=50, verbose_name='Русский')),
                ('match', models.CharField(default='не задано', max_length=50, verbose_name='Математика')),
                ('lit', models.CharField(default='не задано', max_length=50, verbose_name='Лит-ра')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('day', models.CharField(max_length=50, verbose_name='День недели')),
            ],
        ),
    ]
