# Generated by Django 4.0.5 on 2022-06-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашнии задания'},
        ),
    ]
