# Generated by Django 4.0.5 on 2022-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_lit_alter_work_match_alter_work_rus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='day',
        ),
        migrations.AddField(
            model_name='work',
            name='IZO',
            field=models.CharField(default='', max_length=50, verbose_name='Изо'),
        ),
        migrations.AddField(
            model_name='work',
            name='bio',
            field=models.CharField(default='', max_length=50, verbose_name='Биология'),
        ),
        migrations.AddField(
            model_name='work',
            name='eng',
            field=models.CharField(default='', max_length=50, verbose_name='Английский'),
        ),
        migrations.AddField(
            model_name='work',
            name='geo',
            field=models.CharField(default='', max_length=50, verbose_name='География'),
        ),
        migrations.AddField(
            model_name='work',
            name='his',
            field=models.CharField(default='', max_length=50, verbose_name='История'),
        ),
        migrations.AddField(
            model_name='work',
            name='inf',
            field=models.CharField(default='', max_length=50, verbose_name='Информатика'),
        ),
        migrations.AddField(
            model_name='work',
            name='science',
            field=models.CharField(default='', max_length=50, verbose_name='Общество'),
        ),
    ]
