# Generated by Django 4.0.5 on 2022-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_work_day_work_izo_work_bio_work_eng_work_geo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='science',
            field=models.CharField(max_length=50, verbose_name='Общество'),
        ),
    ]
