# Generated by Django 4.0.5 on 2022-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_work_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='IZO',
            field=models.CharField(max_length=50, verbose_name='Изо'),
        ),
        migrations.AlterField(
            model_name='work',
            name='bio',
            field=models.CharField(max_length=50, verbose_name='Биология'),
        ),
        migrations.AlterField(
            model_name='work',
            name='eng',
            field=models.CharField(max_length=50, verbose_name='Английский'),
        ),
        migrations.AlterField(
            model_name='work',
            name='geo',
            field=models.CharField(max_length=50, verbose_name='География'),
        ),
        migrations.AlterField(
            model_name='work',
            name='his',
            field=models.CharField(max_length=50, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='work',
            name='inf',
            field=models.CharField(max_length=50, verbose_name='Информатика'),
        ),
    ]
