# Generated by Django 4.0.5 on 2022-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_work_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=-10800, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='work',
            name='day',
            field=models.CharField(default='Среда', max_length=50, verbose_name='День недели'),
        ),
    ]
