# Generated by Django 4.0.5 on 2022-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_work_date_alter_work_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=(2022, 6, 22, 12, 1, 55, 2, 173, 0), verbose_name='Дата'),
        ),
    ]
