# Generated by Django 4.0.5 on 2022-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=1655888553.4175963, verbose_name='Дата'),
        ),
    ]
