# Generated by Django 4.0.5 on 2022-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_alter_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
