# Generated by Django 4.0.5 on 2022-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_alter_work_deutsch_alter_work_teh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='IZO',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Изо'),
        ),
        migrations.AlterField(
            model_name='work',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Биология'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='work',
            name='day',
            field=models.CharField(blank=True, default='Среда', max_length=50, null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='work',
            name='deutsch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Немецкий'),
        ),
        migrations.AlterField(
            model_name='work',
            name='eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Английский'),
        ),
        migrations.AlterField(
            model_name='work',
            name='geo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='География'),
        ),
        migrations.AlterField(
            model_name='work',
            name='his',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='work',
            name='inf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Информатика'),
        ),
        migrations.AlterField(
            model_name='work',
            name='lit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лит-ра'),
        ),
        migrations.AlterField(
            model_name='work',
            name='match',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Математика'),
        ),
        migrations.AlterField(
            model_name='work',
            name='rus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Русский'),
        ),
        migrations.AlterField(
            model_name='work',
            name='science',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='work',
            name='teh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Технология'),
        ),
    ]
